service: cocktail-backend

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2

functions:
  cocktail:
    handler: handler.cocktail
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: getnonalcococktails/{alcoholic}
          method: get
          cors: true
      - http:
          path: getcocktailbyname/{name}
          method: get
          cors: true
      - http:
          path: getcocktaildrink/{drink1name}/{drink2name}/{drink3name}
          method: get
          cors: true
      - http:
          path: getallcocktails
          method: get
          cors: true
      - http:
          path: cocktail
          method: post
          cors: true        
      - http:
          path: cocktail/{cocktailid}
          method: delete
          cors: true 
      - http:
          path: favourite/{cocktailid}/{username}
          method: put
          cors: true 
      - http:
          path: cocktail/{cocktailid}/{recipe}
          method: put
          cors: true 
